services: 
    postgres:
        image: postgres:16.4
        container_name: task_manager_postgres
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "superuser"
            POSTGRES_PASSWORD: "password"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
            - task-manager-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        mem_limit: 512M
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U superuser -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped

volumes:
    task-manager-data: